name: 'Tests: node.js 8 - 10'

on: [pull_request, push]

jobs:
  tests:
    uses: ljharb/actions/.github/workflows/node.yml@main
    with:
      range: '8 - 10'
      type: minors
      command: npm run tests-only

  node:
    name: 'node 8 - 10'
    needs: [tests]
    runs-on: ubuntu-latest
    steps:
      - run: 'echo tests completed'
